//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUB_EmpleadosDeptos.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EMPLEADO
    {
        public int Codigo { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public string Cargo { get; set; }
        public int Departamento { get; set; }
        public Nullable<decimal> Sueldo { get; set; }
    
        public virtual TBL_DEPARTAMENTO TBL_DEPARTAMENTO { get; set; }
    }
}
